Issue 1
profcomff/timetable-webapp pull request #17
Opened 2022-08-23 06:39 UTC by ilya101master

2022-08-23 07:03 UTC, dyakovri requested changes
Файл с логотипом, кажется, лучше не использовать, а прилинковаться к `/icon-512x512.png`

Запусти форматтер на всех файлах. Все в разнобой, читать неудобно.

2022-08-23 07:03 UTC, dyakovri commented on src/store/index.js
> +      date: new Date('2022-08-19T03:00:00')
Что за хардкод даты?))

2022-08-23 07:03 UTC, dyakovri commented on src/views/Init.vue
> +        </select>
Заюзай плиз бутстраповский стиль

https://getbootstrap.com/docs/5.2/forms/select/

2022-08-23 08:38 UTC, dyakovri commented
![image](https://user-images.githubusercontent.com/5656720/186112792-6ef5b8b7-f7d7-4448-8670-93d515c9e319.png)

Фон натягивается на контейнер с фиксированной шириной, лучше на body наверное
А на боди можно навешивать JSом, главное снимать не забывать

2022-08-23 17:02 UTC, ilya101master commented on package.json
> +    "bootstrap-vue": "^2.22.0",
Удалено

2022-08-23 17:02 UTC, ilya101master commented on src/App.vue
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,400;0,700;1,100;1,400;1,700&display=swap');
Удалено

2022-08-23 19:03 UTC, ilya101master commented on src/components/NavBar.vue
> +    </div>
Нужно починить сайд-бар, кнопки стали лучше

2022-08-23 19:04 UTC, ilya101master commented on src/store/index.js
> +      date: new Date('2022-08-19T03:00:00')
Был костыль, исправлено

2022-08-23 19:05 UTC, ilya101master commented on src/views/Init.vue
> +        </select>
Бутстрап применён

2022-08-23 19:10 UTC, ilya101master commented on src/components/NavBar.vue
> +  <header>
Добавлена

2022-08-24 09:47 UTC, dyakovri commented on package.json
> -    "bootstrap-vue": "^2.22.0",
Ты их просто из файла удалил? Запусти npm install, чтобы обновился файл package-lock.jsob

2022-08-24 09:50 UTC, dyakovri commented on src/views/Init.vue
>          <h1>Добро пожаловать!</h1>
Используй https://cdn.test.profcomff.com/app/logo/icon_512x512.png на тесте и https://cdn.profcomff.com/app/logo/icon_512x512.png на проде

Об использовании окружений читай тут
https://cli.vuejs.org/guide/mode-and-env.html#environment-variables

2022-08-24 09:50 UTC, dyakovri commented on src/views/Init.vue
> +        background-image: url("../assets/background.png");
https://cdn.test.profcomff.com/app/background.png и https://cdn.profcomff.com/app/background.png

2022-08-24 09:52 UTC, dyakovri commented
Закрывай обсуждения, пожалуйста, когда что-то сделал. Вмерджить без закрытых обсуждений нельзя

2022-08-25 01:51 UTC, ilya101master commented on src/views/Init.vue
>          <h1>Добро пожаловать!</h1>
Поставлено, в окружения вынесу все ссылки немного позже

2022-08-25 01:51 UTC, ilya101master commented on package.json
> -    "bootstrap-vue": "^2.22.0",
Всё почищено

2022-08-25 01:57 UTC, ilya101master commented on src/components/NavBar.vue
> +    </div>
цвета и outline пытаюсь починить на стороне aggregator-app

2022-08-25 11:36 UTC, merged