Style fixes
profcomff/timetable-webapp pull request #21
Opened 2022-08-26 03:52 UTC by ilya101master

2022-08-26 08:35 UTC, dyakovri requested changes
Тоже на ярн перешел? 
Ок, только тогда удали package-json.lock, обнови под ярн докеригнор

Не знаю зачем .env через строчку, а не в каждой

По изменениям ок, но надо добавить в сборку среду выполнения
Добавь
- в Dockerfile секцию ARG environment
- и в .github/actions надо этот арг прокинуть в секции сборки

И один коммент оставил

2022-08-26 08:35 UTC, dyakovri commented on src/views/Init.vue
> +  /* background-image: url(v-bind(bgItem)); */
Не вышло? Теперь пустой фон?

2022-08-26 12:54 UTC, ilya101master commented on src/views/Init.vue
> +  /* background-image: url(v-bind(bgItem)); */
Не переходил, видимо просто побочно поставилось, когда запускал навбар. Задний фон вставлен в другом месте в первых строчках, через css не удалось прокинуть.
Можешь чуток подробнее написать, что нужно сделать со средой выполнения

2022-08-29 15:55 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +          build-args: BUILD_MODE=testing
```
build-args: |
    BUILD_MODE=development
```

2022-08-29 15:58 UTC, dyakovri approved these changes

2022-08-29 16:01 UTC, merged